--Q16 DISPLAY CUSTOMERS WHO ARE OLDER THAN 30 YEARS
SELECT *
FROM customers
WHERE EXTRACT(YEAR FROM AGE(CURRENT_DATE,birthday))>30;

--Q17 DISPLAY ALL CUSTOMERS FROM THE UNITED STATES
SELECT * 
FROM customers
WHERE country='United States';

--Q18 DISPLAY ALL PRODUCTS BELONGING TO COMPUTERS CATEGORY
SELECT * 
FROM products
WHERE category='Computers';

--Q19 DISPALY PRODUCTS WITH PRICES BETWEEN 500 & 1000 USD
SELECT * 
FROM products
WHERE CAST(
	REPLACE(
		REPLACE(unit_price_usd,'$',''),
		',','')AS NUMERIC
		)
BETWEEN 500 AND 1000;

--Q20 DISPLAY CUSTOMERS WHOSE NAME START WITH 'A'
SELECT * 
FROM customers
WHERE name LIKE 'A%';

--Q21 DISPLAY CUSTOMERS WHOSE NAME END WITH 'n'
SELECT * 
FROM customers
WHERE name LIKE '_%n';

--Q22  DISPLAY CUSTOMERS FROM US,CANADA,AUSTRALIA
SELECT * 
FROM customers
WHERE country IN ('United States','Canada','Australia');

--Q23  DISPLAY PRODUCTS THAT DO NOT BELONG TO COMPUTERS CATEGORY
SELECT * 
FROM products
WHERE category!='Computers';

--Q24 DISPLAY STORES OPENED AFTER 2010
SELECT * 
FROM stores
WHERE EXTRACT(YEAR FROM open_date)>2010;

--Q25 DISPLAY STORES OPENED BETWEEN 2010 AND 2015
SELECT *
FROM stores
WHERE EXTRACT(YEAR FROM open_date)
BETWEEN 2010 AND 2015;